import { defineNuxtPlugin } from "#app";
import { Amplify, Auth } from "aws-amplify";

import awsmobile from "../aws-exports";
// aws-exports should be dynamically generated by AWS Amplify

export default defineNuxtPlugin((nuxtApp) => {
  Amplify.configure(awsmobile);

  return {
    provide: {
      auth: Auth,
    },
  };
});
